openapi: 3.0.0
info:
  title: Tu! Open Bank API
  description: Tu! Open Bank API
  version: '1.0.0'
# Added by API Auto Mocking Plugin
servers:
  - url: 'https://techu-backend.herokuapp.com'
    variables: {}
    description: Production Environment
  - url: 'https://techu-backend-develop.herokuapp.com'
    variables: {}
    description: Development Environment
  - url: 'http://localhost:3000'
    variables: {}
    description: Local Environment
paths:
  /user:
    get:
      x-swagger-router-controller: User
      operationId: getUsersList
      tags:
        - /user
      summary: Retorna la lista de usuario
      description: Lista de los usuarios del sistema
      responses:
        '200':
          description: retorna lista de usuarios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
    post:
      x-swagger-router-controller: User
      operationId: createUser
      tags:
        - /user
      summary: Crea un usuario
      description: Alta de un usuario con credenciales de login validas
      requestBody:
        required: true
        description: Objecto JSON que contiene un usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: Operación exitosa
  /user/login:
    get:
      x-swagger-router-controller: User
      operationId: loginUser
      tags:
        - /user
      summary: Login del usuario en el sistema
      description: ""
      parameters:
      - name: username
        in: query
        description: Nombre del usuario para el login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: Password del usuario sin encriptar
        required: true
        schema:
          type: string
      responses:
        '200':
          description: operacion exitosa
          content:
            application/json:
              schema:
                type: string
          headers:
            X-Rate-Limit:
              schema:
                type: integer
                format: int32
              description: Invocaciones permitidas por el usuario por hora
            X-Expires-After:
              schema:
                type: string
                format: date-time
              description: date in UTC cuando el token
  /user/logout:
    get:
      x-swagger-router-controller: User
      operationId: logoutUser
      tags:
        - /user
      summary: Logout del usuario del sistema
      description: ""
      parameters: []
      responses:
        default:
          description: Logout exitoso.
  /user/recover:
    get:
      x-swagger-router-controller: User
      operationId: recoverPassword
      tags:
        - /user
      summary: Recupera la password de un usuario enviando el mail
      description: ""
      parameters:
      - name: username
        in: query
        description: Nombre del usuario que necesita recuperar la password
        required: true
        schema:
          type: string
      - name: email
        in: query
        description: Email a donde enviar la password
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Envio de mail exitoso
          content:
            application/json:
              schema:
                type: string
  /account/{accountId}:
    get:
      x-swagger-router-controller: Account
      operationId: getAccount
      tags:
        - /account
      summary: Account detail
      description: Retorna la informacion de una cuenta
      parameters:
        - name: accountId
          in: path
          description: Id de la cuenta
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: retorna info de una cuenta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /product/{productId}:
    get:
      x-swagger-router-controller: Product
      operationId: getProducts
      tags:
        - /product
      summary: detalle de un producto
      description: Retorna la informacion de un producto
      parameters:
        - name: productId
          in: path
          description: Id del producto
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: retorna info de un producto.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /transaction/{accountId}:
    get:
      x-swagger-router-controller: Transaction
      operationId: getTransactionList
      tags:
        - /transaction
      summary: lista de transacciones de una cuenta
      description: Retorna la lista de transacciones de una cuenta
      parameters:
        - name: accountId
          in: path
          description: accountId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: retorna lista de transacciones de una cuenta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionList'
  /transaction/{fromAccountId}:
    post:
      x-swagger-router-controller: Transaction
      operationId: doTransferencia
      tags:
        - /transaction
      summary: Realiza una transferencia
      description: Realiza una transferencia desde el origen al destino, por importe
      parameters:
        - name: fromAccountId
          in: path
          description: cuenta origen
          required: true
          schema:
            type: integer
        - name: toAccountId
          in: path
          description: cuenta destino
          required: true
          schema:
            type: integer
        - name: importe
          in: path
          description: importe
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: retorna la info de la transaccion realizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /transaction/exchange/{fromAccountId}:
    post:
      x-swagger-router-controller: Transaction
      operationId: doExchange
      tags:
        - /transaction
      summary: Realiza una Exchange entre ARS y USD
      description: Realiza una Exchange desde el origen al destino, por importe y tipo de cambio
      parameters:
        - name: fromAccountId
          in: path
          description: cuenta origen
          required: true
          schema:
            type: integer
        - name: toAccountId
          in: path
          description: cuenta destino
          required: true
          schema:
            type: integer
        - name: importeEnUSD
          in: path
          description: importeEnUSD
          required: true
          schema:
            type: integer
        - name: cotizacion
          in: path
          description: cotizacion del tipo de cambio en USD
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: retorna la info de la transaccion realizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /quote/{quoteId}:
    get:
      x-swagger-router-controller: Quote
      operationId: getQuote
      tags:
        - /quote
      summary: Mensajes, textos o promociones
      description: Retorna un mensaje random para el usuario
      parameters:
        - name: quoteId
          in: path
          description: QuoteId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: retorna un mensaje
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    User:
      properties:
        userId:
          type: integer
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        isLogged:
          type: boolean
          default: false
    UserList:
      type: object
      properties:
        products:
          description: User List
          type: array
          items:
            $ref: '#/components/schemas/UserList'
    Account:
      properties:
        userId:
          type: integer
        accountId:
          type: integer
        accountType:
          type: string
        accountBranch:
          type: string
        accountNumber:
          type: string
        accountDV:
          type: string
        accountCurrency:
          type: string
        accountBalance:
          type: integer
    Product:
      properties:
        productId:
          type: integer
        productCode:
          type: string
        productDescription:
          type: string
        productLabel:
          type: string
        productCurrency:
          type: string
        productAmount:
          type: integer
    Transaction:
      properties:
        transactionId:
          type: integer
        userId:
          type: integer
        accountId:
          type: integer
        transactionDate:
          type: string
        transactionDescription:
          type: string
        transactionCurrency:
          type: string
        transactionBalance:
          type: integer
        timestamp:
          type: string
    TransactionList:
      type: object
      properties:
        products:
          description: Transaction List
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Quote:
      properties:
        quoteId:
          type: integer
        text:
          type: string
