defaults: &defaults
  api:
    port: 3000

  logger:
    name: Techu Open API Bank
    level: debug
    levels:
      trace:
      debug: STDOUT
      info:
      warn:
      error: STDERR
      fatal:

development:
  <<: *defaults

production:
  <<: *defaults

  logger:
    name: Techu Open API Bank
    level: debug
    levels:
      trace:
      debug: STDOUT
      # info: ./log/info.log
      # warn: ./log/warn.log
      # error: ./log/error.log
      # fatal: ./log/fatal.log
